name: Build

on:
  push:
    branches: [develop, serenity, euphoria]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo REGISTRY=ghcr.io >> $GITHUB_ENV
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/pyxis-sa-crawler:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=main >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/pyxis-sa >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_EUPHORIA=./clusters/k8s-testnet-euphoria/pyxis-sa >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_SERENITY=./clusters/k8s-testnet-serenity/pyxis-sa >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_pyxis-sa_crawler >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          push: true
          tags: |
            ${{ env.CONTAINER_RELEASE_IMAGE }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          bash ./ci/updateManifest.sh
